# Generated by Django 6.0.7 on 2026-09-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='pending', max_length=20, verbose_name='حالة الطلب'),
        ),
    ]
