# Generated by Django 6.0.7 on 2026-08-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invites', '0005_orderdetails_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='delivery_notes',
            field=models.TextField(blank=True),
        ),
    ]
