# Generated by Django 6.0.7 on 2026-09-08 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invites', '0006_alter_orderdetails_delivery_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='invite_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('accepted', 'تم القبول'), ('rejected', 'تم الرفض')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_info', to='e_invites.order'),
        ),
    ]
