# Generated by Django 6.0.7 on 2026-08-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_category_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='products/', verbose_name='صورة أو فيديو المنتج'),
        ),
    ]
