# Generated by Django 6.0.7 on 2026-08-28 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(max_length=200, verbose_name='مناسبة الدعوة')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='السعر')),
                ('date', models.DateField(verbose_name='تاريخ المناسبة')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('place', models.CharField(max_length=200, verbose_name='المكان')),
                ('names', models.CharField(blank=True, max_length=255, verbose_name='الأسماء المطلوبة')),
                ('message', models.TextField(blank=True, verbose_name='ملاحظات أو عبارة الدعوة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='products_images/', verbose_name='صورة أو فيديو إضافي')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
    ]
