# Generated by Django 6.0.7 on 2026-09-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_tag_productdetail_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_info',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهاتف / واتساب'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم العميل'),
        ),
        migrations.AddField(
            model_name='order',
            name='details',
            field=models.TextField(blank=True, verbose_name='تفاصيل إضافية'),
        ),
        migrations.AddField(
            model_name='order',
            name='invite_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الدعوة'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ المناسبة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='occasion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='مناسبة الدعوة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='المكان'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='السعر'),
        ),
    ]
